Create logout test
Dmaza86/go-qr-selenium pull request #2
Opened 2021-12-31 16:15 UTC by Dmaza86

2021-12-31 16:42 UTC, Jose-Luis-Nunez requested changes

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +
Delete line

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +        clickOnElement(menu)
I would extract the click on menu in an extra function

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    lateinit var signInPage: SignInPage
New line

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +        assertThat(signInPage.url).isEqualTo(url())
Reformat code

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +        assertThat(signInPage.url).isEqualTo(url())
I would not assert on an url better on an element that is only visible when the user is logout

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    @BeforeEach
The idea is nice but I would just put all in the test function

2021-12-31 16:42 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +class LogoutPage : AbstractScreen() {
I think this is not the logout page right ? I think this a screen where you are logged in right ? Or is it maybe the menu element ?

2021-12-31 17:02 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +class LogoutPage : AbstractScreen() {
yeah better use the LanguageMenuPage and rename to only menu and put here the logout stuff

2022-01-01 09:16 UTC, Jose-Luis-Nunez commented
you can have a package menu and this could have 2 subfolders logout and translation

2022-01-01 09:28 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +
done

2022-01-01 09:29 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +        clickOnElement(menu)
done

2022-01-01 09:29 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    lateinit var signInPage: SignInPage
done

2022-01-01 09:29 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +        assertThat(signInPage.url).isEqualTo(url())
done

2022-01-01 09:29 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +        assertThat(signInPage.url).isEqualTo(url())
done

2022-01-01 09:30 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    @BeforeEach
done

2022-01-01 09:30 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/LogoutPage.kt
> +class LogoutPage : AbstractScreen() {
done

2022-01-01 12:05 UTC, Dmaza86 commented
> you can have a package menu and this could have 2 subfolders logout and translation

2022-01-02 10:43 UTC, Jose-Luis-Nunez requested changes

2022-01-02 10:44 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/SignInPage.kt
> +    fun getSignInButton():FluentWebElement{
done

2022-01-02 10:44 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    lateinit var logoutPage: LogoutPage
done

2022-01-02 10:46 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/logout/LogoutTest.kt
> +    lateinit var menuPage: MenuPage
done

2022-01-02 10:46 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/MenuPage.kt
> +class MenuPage : AbstractScreen() {
done

2022-01-02 11:19 UTC, Jose-Luis-Nunez requested changes

2022-01-02 11:19 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/MenuBar.kt
> +    }
we need still to improve this

2022-01-02 12:07 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/MenuBar.kt
> +    }
done

2022-01-02 12:45 UTC, Jose-Luis-Nunez approved these changes

2022-01-02 14:16 UTC, merged