Customer can rate the service
Dmaza86/go-qr-selenium pull request #5
Opened 2022-01-06 16:08 UTC by Dmaza86

2022-01-06 17:30 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
The test is unstable at this point, sometimes it passes, sometimes it doesn't. Shows the correct URL.

2022-01-06 18:35 UTC, Jose-Luis-Nunez requested changes

2022-01-06 18:35 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(url()).isEqualTo(expectedURL)
i would test that the feedbackField is not visible after you submit the feedback to not assert on the url

2022-01-06 18:35 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(url()).isEqualTo(expectedURL)
same here

2022-01-06 18:43 UTC, Jose-Luis-Nunez requested changes

2022-01-06 18:43 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
i would not use thankForFeedback as an extra function to wait for an element, better use the wait in the function where you need it

2022-01-06 18:43 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    fun thankForFeedback() {
i would not use thankForFeedback as an extra function to wait for an element, better use the wait in the function where you need it

2022-01-06 18:44 UTC, Jose-Luis-Nunez requested changes

2022-01-06 18:44 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
same here regarding the wait

2022-01-06 19:12 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(url()).isEqualTo(expectedURL)
done

2022-01-06 19:12 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(url()).isEqualTo(expectedURL)
done

2022-01-06 19:12 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
done

2022-01-06 19:13 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
done

2022-01-06 19:13 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    fun thankForFeedback() {
done

2022-01-06 19:14 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +            thankForFeedback()
done

2022-01-06 19:14 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(url()).isEqualTo(expectedURL)
done

2022-01-06 20:28 UTC, Jose-Luis-Nunez requested changes

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    fun disappearFeedbackField(): Boolean {
better just return the Element and assert in the test that it is not displayed

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +        waitUntilElementDisplayed(text)
why do you wait hier to wait for the text?

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +        waitUntilElementDisplayed(text)
could you wait for something else? or is the wait here necessary?

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    private lateinit var text: FluentWebElement
i would recommend to give a better name, not "text"

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(customerFeedbackPage.disappearFeedbackField()).isTrue
better just return the Element and assert in the test that it is not displayed

2022-01-06 20:28 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(customerFeedbackPage.disappearFeedbackField()).isTrue
better just return the Element and assert in the test that it is not displayed

2022-01-06 20:37 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +        waitUntilElementDisplayed(text)
I think that it helps to slow down the test, and for  the assert to pass

2022-01-07 10:55 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    fun disappearFeedbackField(): Boolean {
I changed it for an element and the assert for Is not present

2022-01-07 10:56 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    private lateinit var text: FluentWebElement
done

2022-01-07 10:56 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(customerFeedbackPage.disappearFeedbackField()).isTrue
I changed it for an element and the assert for Is not present

2022-01-07 10:56 UTC, Dmaza86 commented on src/test/kotlin/tests/goqr/customerfeedback/CustomerFeedbackTest.kt
> +        assertThat(customerFeedbackPage.disappearFeedbackField()).isTrue
I changed it for an element and the assert for Is not present

2022-01-07 22:17 UTC, Jose-Luis-Nunez requested changes

2022-01-07 22:17 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/goqr/customerfeedback/CustomerFeedbackPage.kt
> +    fun getFeedbackField(): FluentWebElement {
here you are not getting the feedbackField, you are getting the feedbackDone element but this element is visible on both screens on the screen where the user can type a feedback and also on the screen after the user enters the feedback. you need to get an Element that is only visible on the first screen.

that is also the reason why you can wait until the element is displayed but you assert that it is not present --> the reason ist because it is visible on twice^^before you submit your feedback and after you submit the feedback.

if you want to assert that a element is not displayed i cannot recommend you to wait until it is displayed^^

2022-01-11 12:27 UTC, Jose-Luis-Nunez approved these changes

2022-01-11 13:11 UTC, merged